import React from 'react';

import Head from 'next/head';

import DOMPurify from 'dompurify';
import {marked} from 'marked';

import styles from '../styles/Home.module.css';



marked.setOptions({
	headerIds: false
});

export default function HomePage ({}) {
	const contentElement = React.useRef();
	const editorElement = React.useRef();

	const [content, setContent] = React.useState('');

	const handleChange = (e) => {
		const inputText = e.target.value.trim();
		const unsafeHtml = marked.parse(inputText);
		const safeHtml = DOMPurify.sanitize(unsafeHtml);
		console.log(safeHtml);
		setContent(safeHtml);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>mdLive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className="bg-slate-200 text-center">
				<nav className="max-w-xl mx-auto rounded-b shadow bg-white px-4 py-4">
					<h4>Welcome to <a href="https://github.com/iaseth/mdlive">mdLive</a></h4>
				</nav>
			</header>

			<main className="bg-slate-200 py-6">
				<section className="max-w-7xl mx-auto min-h-screen shadow flex ch:basis-0 ch:grow">
					<div className="bg-white">
						<div className="font-bold text-center bg-slate-100 px-2 py-4">
							<h4>Live</h4>
						</div>
						<div>
							<div ref={contentElement} dangerouslySetInnerHTML={{__html: content}} className="px-3 py-2"></div>
						</div>
					</div>
					<div className="bg-slate-100 flex flex-col border-l-2 border-slate-500">
						<div>
							<h4 className="font-bold text-center bg-slate-100 px-2 py-4">Edit</h4>
						</div>
						<div className="grow bg-white">
							<textarea ref={editorElement} onChange={handleChange} className="bg-editor w-full h-full px-3 leading-[32px] bg-transparent resize-none outline-0"></textarea>
						</div>
					</div>
				</section>
			</main>

			<footer className="bg-slate-200 text-center">
				<nav className="max-w-xl mx-auto rounded-t shadow bg-white px-4 py-12">
					<h4>Created by Ankur Seth.</h4>
					<div className="h-2" />
					<h4>View source on GitHub.</h4>
				</nav>
			</footer>
		</div>
	);
}
